FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
ARG NUGET_USERNAME=${NUGET_USERNAME}
ARG NUGET_PWD=${NUGET_PWD}

WORKDIR /src
COPY ["EcoSensorApi.csproj", "EcoSensorApi/"]
RUN dotnet nuget add source --username ${NUGET_USERNAME} --password ${NUGET_PWD} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/EMP-Projects/index.json"
RUN dotnet restore "EcoSensorApi/EcoSensorApi.csproj"
WORKDIR "/src/EcoSensorApi"
COPY . .
RUN dotnet build "EcoSensorApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "EcoSensorApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EcoSensorApi.dll"]
