// <auto-generated />
using System;
using EcoSensorApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace EcoSensorApi.Migrations
{
    [DbContext(typeof(EcoSensorDbContext))]
    partial class EcoSensorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoSensorApi.AirQuality.Indexes.Eu.EuAirQualityLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_key");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<double>("Max")
                        .HasColumnType("double precision")
                        .HasColumnName("max");

                    b.Property<double>("Min")
                        .HasColumnType("double precision")
                        .HasColumnName("min");

                    b.Property<TimeSpan>("Period")
                        .HasColumnType("interval")
                        .HasColumnName("period");

                    b.Property<int>("Pollution")
                        .HasColumnType("integer")
                        .HasColumnName("pollution");

                    b.Property<NpgsqlTsVector>("SearchText")
                        .HasColumnType("tsvector")
                        .HasColumnName("search_text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("EntityKey");

                    b.ToTable("eu_air_quality_index");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "#47EEE0",
                            EntityKey = "Eu AirQuality Level",
                            Level = 0,
                            Max = 10.0,
                            Min = 0.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(4440),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 2L,
                            Color = "#44C39A",
                            EntityKey = "Eu AirQuality Level",
                            Level = 1,
                            Max = 20.0,
                            Min = 10.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8330),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 3L,
                            Color = "#ECE433",
                            EntityKey = "Eu AirQuality Level",
                            Level = 2,
                            Max = 25.0,
                            Min = 20.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8330),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 4L,
                            Color = "#E8333C",
                            EntityKey = "Eu AirQuality Level",
                            Level = 3,
                            Max = 50.0,
                            Min = 25.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8340),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 5L,
                            Color = "#820026",
                            EntityKey = "Eu AirQuality Level",
                            Level = 4,
                            Max = 75.0,
                            Min = 50.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8340),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 6L,
                            Color = "#680D6D",
                            EntityKey = "Eu AirQuality Level",
                            Level = 5,
                            Max = 800.0,
                            Min = 75.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8340),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 7L,
                            Color = "#47EEE0",
                            EntityKey = "Eu AirQuality Level",
                            Level = 0,
                            Max = 20.0,
                            Min = 0.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8350),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 8L,
                            Color = "#44C39A",
                            EntityKey = "Eu AirQuality Level",
                            Level = 1,
                            Max = 40.0,
                            Min = 20.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8350),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 9L,
                            Color = "#ECE433",
                            EntityKey = "Eu AirQuality Level",
                            Level = 2,
                            Max = 50.0,
                            Min = 40.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8350),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 10L,
                            Color = "#E8333C",
                            EntityKey = "Eu AirQuality Level",
                            Level = 3,
                            Max = 100.0,
                            Min = 50.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8350),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 11L,
                            Color = "#820026",
                            EntityKey = "Eu AirQuality Level",
                            Level = 4,
                            Max = 150.0,
                            Min = 100.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8350),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 12L,
                            Color = "#680D6D",
                            EntityKey = "Eu AirQuality Level",
                            Level = 5,
                            Max = 1200.0,
                            Min = 150.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8380),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 13L,
                            Color = "#47EEE0",
                            EntityKey = "Eu AirQuality Level",
                            Level = 0,
                            Max = 40.0,
                            Min = 0.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8390),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 14L,
                            Color = "#44C39A",
                            EntityKey = "Eu AirQuality Level",
                            Level = 1,
                            Max = 90.0,
                            Min = 40.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8410),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 15L,
                            Color = "#ECE433",
                            EntityKey = "Eu AirQuality Level",
                            Level = 2,
                            Max = 120.0,
                            Min = 90.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8410),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 16L,
                            Color = "#E8333C",
                            EntityKey = "Eu AirQuality Level",
                            Level = 3,
                            Max = 230.0,
                            Min = 120.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8410),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 17L,
                            Color = "#820026",
                            EntityKey = "Eu AirQuality Level",
                            Level = 4,
                            Max = 340.0,
                            Min = 230.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8410),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 18L,
                            Color = "#680D6D",
                            EntityKey = "Eu AirQuality Level",
                            Level = 5,
                            Max = 1000.0,
                            Min = 340.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8420),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 19L,
                            Color = "#47EEE0",
                            EntityKey = "Eu AirQuality Level",
                            Level = 0,
                            Max = 50.0,
                            Min = 0.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8420),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 20L,
                            Color = "#44C39A",
                            EntityKey = "Eu AirQuality Level",
                            Level = 1,
                            Max = 100.0,
                            Min = 50.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8420),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 21L,
                            Color = "#ECE433",
                            EntityKey = "Eu AirQuality Level",
                            Level = 2,
                            Max = 130.0,
                            Min = 100.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8420),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 22L,
                            Color = "#E8333C",
                            EntityKey = "Eu AirQuality Level",
                            Level = 3,
                            Max = 240.0,
                            Min = 130.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8420),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 23L,
                            Color = "#820026",
                            EntityKey = "Eu AirQuality Level",
                            Level = 4,
                            Max = 380.0,
                            Min = 240.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8430),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 24L,
                            Color = "#680D6D",
                            EntityKey = "Eu AirQuality Level",
                            Level = 5,
                            Max = 800.0,
                            Min = 380.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8440),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 25L,
                            Color = "#47EEE0",
                            EntityKey = "Eu AirQuality Level",
                            Level = 0,
                            Max = 100.0,
                            Min = 0.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8450),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 26L,
                            Color = "#44C39A",
                            EntityKey = "Eu AirQuality Level",
                            Level = 1,
                            Max = 200.0,
                            Min = 100.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8450),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 27L,
                            Color = "#ECE433",
                            EntityKey = "Eu AirQuality Level",
                            Level = 2,
                            Max = 350.0,
                            Min = 200.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8450),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 28L,
                            Color = "#E8333C",
                            EntityKey = "Eu AirQuality Level",
                            Level = 3,
                            Max = 500.0,
                            Min = 350.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8460),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 29L,
                            Color = "#820026",
                            EntityKey = "Eu AirQuality Level",
                            Level = 4,
                            Max = 750.0,
                            Min = 500.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8460),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 30L,
                            Color = "#680D6D",
                            EntityKey = "Eu AirQuality Level",
                            Level = 5,
                            Max = 1250.0,
                            Min = 750.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8460),
                            Unit = "μg/m3"
                        });
                });

            modelBuilder.Entity("EcoSensorApi.AirQuality.Indexes.Us.UsAirQualityLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_key");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<double>("Max")
                        .HasColumnType("double precision")
                        .HasColumnName("max");

                    b.Property<double>("Min")
                        .HasColumnType("double precision")
                        .HasColumnName("min");

                    b.Property<TimeSpan>("Period")
                        .HasColumnType("interval")
                        .HasColumnName("period");

                    b.Property<int>("Pollution")
                        .HasColumnType("integer")
                        .HasColumnName("pollution");

                    b.Property<NpgsqlTsVector>("SearchText")
                        .HasColumnType("tsvector")
                        .HasColumnName("search_text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("EntityKey");

                    b.ToTable("us_air_quality_index");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "#47EEE0",
                            EntityKey = "Us AirQuality Level",
                            Level = 0,
                            Max = 55.0,
                            Min = 0.0,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 255, DateTimeKind.Utc).AddTicks(8870),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 2L,
                            Color = "#44C39A",
                            EntityKey = "Us AirQuality Level",
                            Level = 1,
                            Max = 70.0,
                            Min = 55.0,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3080),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 3L,
                            Color = "#ECE433",
                            EntityKey = "Us AirQuality Level",
                            Level = 2,
                            Max = 85.0,
                            Min = 70.0,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3080),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 4L,
                            Color = "#E8333C",
                            EntityKey = "Us AirQuality Level",
                            Level = 3,
                            Max = 105.0,
                            Min = 85.0,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3080),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 5L,
                            Color = "#820026",
                            EntityKey = "Us AirQuality Level",
                            Level = 4,
                            Max = 200.0,
                            Min = 105.0,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3120),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 6L,
                            Color = "#ECE433",
                            EntityKey = "Us AirQuality Level",
                            Level = 2,
                            Max = 165.0,
                            Min = 125.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3120),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 7L,
                            Color = "#E8333C",
                            EntityKey = "Us AirQuality Level",
                            Level = 3,
                            Max = 205.0,
                            Min = 165.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3120),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 8L,
                            Color = "#820026",
                            EntityKey = "Us AirQuality Level",
                            Level = 4,
                            Max = 405.0,
                            Min = 205.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3120),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 9L,
                            Color = "#680D6D",
                            EntityKey = "Us AirQuality Level",
                            Level = 5,
                            Max = 605.0,
                            Min = 405.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 3,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3130),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 10L,
                            Color = "#47EEE0",
                            EntityKey = "Us AirQuality Level",
                            Level = 0,
                            Max = 12.0,
                            Min = 0.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3130),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 11L,
                            Color = "#44C39A",
                            EntityKey = "Us AirQuality Level",
                            Level = 1,
                            Max = 35.5,
                            Min = 12.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3130),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 12L,
                            Color = "#ECE433",
                            EntityKey = "Us AirQuality Level",
                            Level = 2,
                            Max = 55.5,
                            Min = 35.5,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3130),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 13L,
                            Color = "#E8333C",
                            EntityKey = "Us AirQuality Level",
                            Level = 3,
                            Max = 105.5,
                            Min = 55.5,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3140),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 14L,
                            Color = "#820026",
                            EntityKey = "Us AirQuality Level",
                            Level = 4,
                            Max = 250.5,
                            Min = 150.5,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3200),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 15L,
                            Color = "#680D6D",
                            EntityKey = "Us AirQuality Level",
                            Level = 5,
                            Max = 500.5,
                            Min = 250.5,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 7,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3200),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 16L,
                            Color = "#47EEE0",
                            EntityKey = "Us AirQuality Level",
                            Level = 0,
                            Max = 55.0,
                            Min = 0.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3200),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 17L,
                            Color = "#44C39A",
                            EntityKey = "Us AirQuality Level",
                            Level = 1,
                            Max = 155.0,
                            Min = 55.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3220),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 18L,
                            Color = "#ECE433",
                            EntityKey = "Us AirQuality Level",
                            Level = 2,
                            Max = 255.0,
                            Min = 155.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3220),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 19L,
                            Color = "#E8333C",
                            EntityKey = "Us AirQuality Level",
                            Level = 3,
                            Max = 355.0,
                            Min = 255.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3220),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 20L,
                            Color = "#820026",
                            EntityKey = "Us AirQuality Level",
                            Level = 4,
                            Max = 425.0,
                            Min = 355.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3220),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 21L,
                            Color = "#680D6D",
                            EntityKey = "Us AirQuality Level",
                            Level = 5,
                            Max = 605.0,
                            Min = 425.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 6,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3230),
                            Unit = "μg/m3"
                        },
                        new
                        {
                            Id = 22L,
                            Color = "#47EEE0",
                            EntityKey = "Us AirQuality Level",
                            Level = 0,
                            Max = 4.5,
                            Min = 0.0,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 0,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3230),
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 23L,
                            Color = "#44C39A",
                            EntityKey = "Us AirQuality Level",
                            Level = 1,
                            Max = 9.5,
                            Min = 4.5,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 0,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3230),
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 24L,
                            Color = "#ECE433",
                            EntityKey = "Us AirQuality Level",
                            Level = 2,
                            Max = 12.5,
                            Min = 9.5,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 0,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3230),
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 25L,
                            Color = "#E8333C",
                            EntityKey = "Us AirQuality Level",
                            Level = 3,
                            Max = 15.5,
                            Min = 12.5,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 0,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3230),
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 26L,
                            Color = "#820026",
                            EntityKey = "Us AirQuality Level",
                            Level = 4,
                            Max = 30.5,
                            Min = 15.5,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 0,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3240),
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 27L,
                            Color = "#680D6D",
                            EntityKey = "Us AirQuality Level",
                            Level = 5,
                            Max = 50.5,
                            Min = 30.5,
                            Period = new TimeSpan(0, 8, 0, 0, 0),
                            Pollution = 0,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3240),
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 28L,
                            Color = "#47EEE0",
                            EntityKey = "Us AirQuality Level",
                            Level = 0,
                            Max = 35.0,
                            Min = 0.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3250),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 29L,
                            Color = "#44C39A",
                            EntityKey = "Us AirQuality Level",
                            Level = 1,
                            Max = 75.0,
                            Min = 35.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3250),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 30L,
                            Color = "#ECE433",
                            EntityKey = "Us AirQuality Level",
                            Level = 2,
                            Max = 185.0,
                            Min = 75.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3260),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 31L,
                            Color = "#E8333C",
                            EntityKey = "Us AirQuality Level",
                            Level = 3,
                            Max = 305.0,
                            Min = 185.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3260),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 32L,
                            Color = "#820026",
                            EntityKey = "Us AirQuality Level",
                            Level = 4,
                            Max = 605.0,
                            Min = 305.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3260),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 33L,
                            Color = "#680D6D",
                            EntityKey = "Us AirQuality Level",
                            Level = 5,
                            Max = 1005.0,
                            Min = 605.0,
                            Period = new TimeSpan(1, 0, 0, 0, 0),
                            Pollution = 2,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3260),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 34L,
                            Color = "#47EEE0",
                            EntityKey = "Us AirQuality Level",
                            Level = 0,
                            Max = 54.0,
                            Min = 0.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3270),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 35L,
                            Color = "#44C39A",
                            EntityKey = "Us AirQuality Level",
                            Level = 1,
                            Max = 100.0,
                            Min = 54.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3270),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 36L,
                            Color = "#ECE433",
                            EntityKey = "Us AirQuality Level",
                            Level = 2,
                            Max = 360.0,
                            Min = 100.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3270),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 37L,
                            Color = "#E8333C",
                            EntityKey = "Us AirQuality Level",
                            Level = 3,
                            Max = 650.0,
                            Min = 360.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3270),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 38L,
                            Color = "#820026",
                            EntityKey = "Us AirQuality Level",
                            Level = 4,
                            Max = 1250.0,
                            Min = 650.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3270),
                            Unit = "ppb"
                        },
                        new
                        {
                            Id = 39L,
                            Color = "#680D6D",
                            EntityKey = "Us AirQuality Level",
                            Level = 5,
                            Max = 2050.0,
                            Min = 1250.0,
                            Period = new TimeSpan(0, 1, 0, 0, 0),
                            Pollution = 1,
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 256, DateTimeKind.Utc).AddTicks(3280),
                            Unit = "ppb"
                        });
                });

            modelBuilder.Entity("EcoSensorApi.AirQuality.Properties.AirQualityPropertiesModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<double>("Elevation")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_key");

                    b.Property<long?>("EuropeanAqi")
                        .HasColumnType("bigint")
                        .HasColumnName("european_aqi");

                    b.Property<long>("GisId")
                        .HasColumnType("bigint")
                        .HasColumnName("gis_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("Pollution")
                        .HasColumnType("integer")
                        .HasColumnName("pollution");

                    b.Property<NpgsqlTsVector>("SearchText")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_text")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "EntityKey" });

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("TypeMonitoringData")
                        .HasColumnType("integer")
                        .HasColumnName("type_monitoring_data");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unit");

                    b.Property<long?>("UsAqi")
                        .HasColumnType("bigint")
                        .HasColumnName("us_aqi");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("EntityKey");

                    b.HasIndex("GisId");

                    b.HasIndex("SearchText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "GIN");

                    b.ToTable("air_quality_measures");
                });

            modelBuilder.Entity("EcoSensorApi.AirQuality.Vector.AirQualityVectorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_key");

                    b.Property<long>("EntityVectorId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_vector_id");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geom");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<NpgsqlTsVector>("SearchText")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_text")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "EntityKey" });

                    b.Property<int>("SourceData")
                        .HasColumnType("integer")
                        .HasColumnName("source_data");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("TypeMonitoringData")
                        .HasColumnType("integer")
                        .HasColumnName("type_monitoring_data");

                    b.HasKey("Id");

                    b.HasIndex("EntityKey");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("SearchText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "GIN");

                    b.ToTable("air_quality");
                });

            modelBuilder.Entity("EcoSensorApi.Config.ConfigModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CityCode")
                        .HasColumnType("integer")
                        .HasColumnName("city_code");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("city_name");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_key");

                    b.Property<int>("ProvCode")
                        .HasColumnType("integer")
                        .HasColumnName("prov_code");

                    b.Property<string>("ProvName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prov_name");

                    b.Property<int>("RegionCode")
                        .HasColumnType("integer")
                        .HasColumnName("region_code");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region_name");

                    b.Property<NpgsqlTsVector>("SearchText")
                        .HasColumnType("tsvector")
                        .HasColumnName("search_text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("TypeMonitoringData")
                        .HasColumnType("integer")
                        .HasColumnName("type_monitoring_data");

                    b.HasKey("Id");

                    b.HasIndex("EntityKey");

                    b.ToTable("layers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CityCode = 72021,
                            CityName = "Gioia del Colle",
                            EntityKey = "ad045871-1532-4a74-82f5-ab870d8f896b",
                            ProvCode = 72,
                            ProvName = "Bari",
                            RegionCode = 16,
                            RegionName = "Puglia",
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 548, DateTimeKind.Utc).AddTicks(3090),
                            TypeMonitoringData = 0
                        },
                        new
                        {
                            Id = 2L,
                            CityCode = 52032,
                            CityName = "Siena",
                            EntityKey = "Siena",
                            ProvCode = 52,
                            ProvName = "Siena",
                            RegionCode = 9,
                            RegionName = "Toscana",
                            TimeStamp = new DateTime(2024, 9, 22, 13, 26, 10, 548, DateTimeKind.Utc).AddTicks(3120),
                            TypeMonitoringData = 0
                        });
                });

            modelBuilder.Entity("Gis.Net.Osm.OsmPg.Properties.OsmPropertiesModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_key");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<NpgsqlTsVector>("SearchText")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_text")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "EntityKey" });

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EntityKey");

                    b.HasIndex("SearchText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "GIN");

                    b.ToTable("osm_properties");
                });

            modelBuilder.Entity("Gis.Net.Osm.OsmPg.Vector.OsmVectorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_key");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geom");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<long>("IdProperties")
                        .HasColumnType("bigint")
                        .HasColumnName("id_properties");

                    b.Property<NpgsqlTsVector>("SearchText")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_text")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "EntityKey" });

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("EntityKey");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("IdProperties");

                    b.HasIndex("SearchText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "GIN");

                    b.ToTable("osm_vector");
                });

            modelBuilder.Entity("EcoSensorApi.AirQuality.Properties.AirQualityPropertiesModel", b =>
                {
                    b.HasOne("EcoSensorApi.AirQuality.Vector.AirQualityVectorModel", "Gis")
                        .WithMany("PropertiesCollection")
                        .HasForeignKey("GisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gis");
                });

            modelBuilder.Entity("Gis.Net.Osm.OsmPg.Vector.OsmVectorModel", b =>
                {
                    b.HasOne("Gis.Net.Osm.OsmPg.Properties.OsmPropertiesModel", "Properties")
                        .WithMany()
                        .HasForeignKey("IdProperties")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("EcoSensorApi.AirQuality.Vector.AirQualityVectorModel", b =>
                {
                    b.Navigation("PropertiesCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
