name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --build-arg NUGET_USERNAME=${{secrets.NUGET_USERNAME}} --build-arg NUGET_PWD=${{secrets.NUGET_PWD}} --tag emp/ecosensor:$(date +%s) ./backend 
